language: node_js

node_js:
  - 10

cache: yarn

before_install:
  - yarn global add lerna

install:
  - lerna bootstrap

before_script:
  - yarn copy-monaco

matrix:
  include:
    - name: 'Editor Pipeline'
      env:
        - PACKAGE_LOCATION=packages/editor
        - PACKAGE_NAME=editor
    - name: 'Server Pipeline'
      env:
        - PACKAGE_LOCATION=packages/server
        - PACKAGE_NAME=server

script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build

deploy:
  - provider: azure_web_apps
    site: script-lab-react
    slot: alpha
    username: $DEPLOYMENT_USERNAME
    password: $DEPLOYMENT_PASSWORD
    before_deploy:
      - cd build
    after_deploy:
      - cd ../
    on:
      branch: master
      condition: $PACKAGE_NAME = editor

  - provider: azure_web_apps
    site: script-lab-react
    slot: beta
    username: $DEPLOYMENT_USERNAME
    password: $DEPLOYMENT_PASSWORD
    before_deploy:
      - cd build
    after_deploy:
      - cd ../
    on:
      branch: beta
      condition: $PACKAGE_NAME = editor

  - provider: azure_web_apps
    site: script-lab-react
    username: $DEPLOYMENT_USERNAME
    password: $DEPLOYMENT_PASSWORD
    before_deploy:
      - cd build
    after_deploy:
      - cd ../
    on:
      branch: production
      condition: $PACKAGE_NAME = editor

  # script:
#   - lerna run test --stream

# - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test; fi'
# - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn build; fi'

# after_success:
#   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy; fi'

# jobs:
#   include:
#     - stage: editor
#       if: tag =~ ^[0-9]+.[0-9]+.[0-9]+
#       node_js: '8'
#       script: yarn commons:prepare-release
#       before_deploy:
#         - cd release/ringcentral-integration
#       after_deploy:
#         - cd ../../
#       deploy:
#         provider: npm
#         email: embbnux@embbnux.com
#         skip_cleanup: true
#         api_key:
#           secure: Cpjded9XcB31vU0VXGlqkJX8jT/xX5diLbxZ7/dMT3g7zpEt5dgxVaWdGXEIN/klxQHrjgE/K2fMUEqtgFb7lbrk8EKgOSU3vy52h/NIgbC4tHE+8A6hoSk8DgbNNjiCZY4DjLS4EiUjbhyYUHog5ri/TPWfmfQW+XiVcWOu61WIzlm0ia0EVI+RcqbRvzf8YKFkVaVvqPu2cvfDPYBfzmn1u32hZtEzZR6VAtJBI0hhpeIj+97BxhgmNt5MmGf+q3ex0YnE0/9Qv74JT5KSUhjOQjGNEUW15GwTpWn083KKVG8RXGHvrtjvOwMVKRE3VVB64urNkOEODFcz1Yy0C0Nsv+EVYgR2F+yUXcwFOYPGPPC/a/7X8l+sxCBtDgZ3LomWSES1pBJvhtNNZt3/mhGaFB5pqBZeDAXCwlm3ysLOri0lcp25oNKdIbAMAl9PQOc5MmTtDX1dQ4XRCxq+GyHqAo3YcK/VX4sGNcCU/4a6fPi4VDyijzT5VQ709PJ4Zva5jc1qX/GFS9gmMgdr2hb5rhM9/M76WoRIaEe8YaxaaElrl5lBQsWY6e6ipGJRVXGh9ESRz5cYev7YqW/4ihzChZRad+VO7dzalWU8Xea56LmDjFuWSKzJTDNNKrNoGDHgMSm6fOlDhxgSFTVSRX6Pnqaf5UGqu2hQcjnK8So=
#         on:
#           node: '8'
#           tags: true
#           condition: '$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+'
#     - stage: commons script release
#       node_js: '8'
#       if: branch = master AND type = push
#       script: yarn commons:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn commons:start-release
#     - stage: widgets npm release
#       if: tag =~ ^[0-9]+.[0-9]+.[0-9]+
#       node_js: '8'
#       script: yarn widgets:prepare-release
#       before_deploy:
#         - cd release/ringcentral-widgets
#       after_deploy:
#         - cd ../../
#       deploy:
#         provider: npm
#         email: embbnux@embbnux.com
#         skip_cleanup: true
#         api_key:
#           secure: Cpjded9XcB31vU0VXGlqkJX8jT/xX5diLbxZ7/dMT3g7zpEt5dgxVaWdGXEIN/klxQHrjgE/K2fMUEqtgFb7lbrk8EKgOSU3vy52h/NIgbC4tHE+8A6hoSk8DgbNNjiCZY4DjLS4EiUjbhyYUHog5ri/TPWfmfQW+XiVcWOu61WIzlm0ia0EVI+RcqbRvzf8YKFkVaVvqPu2cvfDPYBfzmn1u32hZtEzZR6VAtJBI0hhpeIj+97BxhgmNt5MmGf+q3ex0YnE0/9Qv74JT5KSUhjOQjGNEUW15GwTpWn083KKVG8RXGHvrtjvOwMVKRE3VVB64urNkOEODFcz1Yy0C0Nsv+EVYgR2F+yUXcwFOYPGPPC/a/7X8l+sxCBtDgZ3LomWSES1pBJvhtNNZt3/mhGaFB5pqBZeDAXCwlm3ysLOri0lcp25oNKdIbAMAl9PQOc5MmTtDX1dQ4XRCxq+GyHqAo3YcK/VX4sGNcCU/4a6fPi4VDyijzT5VQ709PJ4Zva5jc1qX/GFS9gmMgdr2hb5rhM9/M76WoRIaEe8YaxaaElrl5lBQsWY6e6ipGJRVXGh9ESRz5cYev7YqW/4ihzChZRad+VO7dzalWU8Xea56LmDjFuWSKzJTDNNKrNoGDHgMSm6fOlDhxgSFTVSRX6Pnqaf5UGqu2hQcjnK8So=
#         on:
#           node: '8'
#           tags: true
#           condition: '$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+'
#     - stage: widgets script release
#       if: branch = master AND type = push
#       node_js: '8'
#       script: yarn widgets:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn widgets:start-release
#     - stage: widgets docs build
#       if: tag =~ ^[0-9]+.[0-9]+.[0-9]+
#       node_js: '8'
#       before_deploy:
#         - lerna run --scope ringcentral-widgets-docs build --stream
#       deploy:
#         provider: pages
#         skip_cleanup: true
#         github_token: $GITHUB_PAGES_TOKEN
#         local_dir: packages/ringcentral-widgets-docs/gh-pages
#         email: 'integrations@ringcentral.com'
#         name: 'RingCentral Integrations Team'
#         on:
#           node: '8'
#           tags: true
#           condition: '$TRAVIS_TAG =~ ^[0-9]+.[0-9]+.[0-9]+'
#     - stage: i18n script release
#       node_js: '8'
#       if: branch = master AND type = push
#       script: yarn i18n:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn i18n:start-release
#     - stage: locale loader script release
#       node_js: '8'
#       if: branch = master AND type = push
#       script: yarn locale-loader:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn locale-loader:start-release
#     - stage: phone number script release
#       node_js: '8'
#       if: branch = master AND type = push
#       script: yarn phone-number:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn phone-number:start-release
#     - stage: glip widgets script release
#       if: branch = master AND type = push
#       node_js: '8'
#       script: yarn glip-widgets:prepare-release
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: yarn glip-widgets:start-release
env:
  global:
    - HTTPS=true
    - secure: HexcEzdxAUC8YRm/qckg678+VYwbgn1yNdgtCtGDHX3ojgoQBQuMVMLFgflQE7YgaiZLU/4srND+IEDeLsVUjRTsI2uKPjxQup46sXiiTbo3r3Asc1Y99O8DsmnXwHKn9O2MZRfUwO5FpsMoq7ERrvrVC/uk5U4+CsPMapz633fHq6/NzdCMYG9J5BI+NuirxJPXOkw1rb+22hsCBGiGeYCEaEmgZppSy5IXLJU4YMLauqEQrq8KZEYaecObpqlA762oGG273WW0PdOMra1clkZMfScP6Z5S3A7K4Q7lDw1t5JOASX7Ongy4x46pqchr7hwGrAazWX7HziLQXcrjjAHzh0Le/yS1QfnRRlxc9fhTAhx14cA0oKrWvLXMAVk8uWPDprOIKHnmNKtCFWpcM6w6Ks9+1Ij7AP+BWt7whFuy8Ta2IPUDLsLAjaMZe9JOwpCGWZSseHpnoMTxLwfCv+yyP/6KdqR346NttCXW60jAb0a5bZQ41UEAi56f7Mxy7ffY8//25tx59jbwBZxgdHxvy5BWOQQ8bcNzGiorxQOxArwyBFEroi+6X0jt3APxjMpWSqQlxn7OncvEeBXDbDiaYhGPJctqfX8cW2QBjKpyfAx0axxbslivVW0ENLaasdc0Pd6IiTIqmiHq93yVIFq8BpJooEtaEzAlkHhc7xc=
    - secure: SiUgnxWC6yqYbgkPMyNnfo94maLXw9FfIKg6Qkj1qxjME2AnwAOSYyI2TXBtLoeHza31ZPFh8CPKeacvoUyiPhfOaufZMG0K6bV5tKFgHsl3OagYV+aui26Vuu/uTo9FBt9tVmHTmdMl5FlXV6UleqtQpjOTGZXOGOIVYbVGMk0G2+p0FkMDU6fadJVXloc8a7izg7rrpbMng5VTGqg3M/qZ8chul3li55Z6LUpYUzN13Pc2uIkAtWGt+W5ZF62xytScudklWkQRsFIAr7pOP253/x7th71jAT0Th8ijpdQGmoXev23phLG1oI5ba1pkBqljxsFeK8MYvDNeBFtE6att0B2x+irOXMlbxaZIXWU3/isAOHVQH5No1+Irmp8vq2gajtaVCAurU4WNGgsAiKrZ7gxqzq3FOpcshRgFlIVkDuoHboAMEYjR/IsGdZPuvFFNWK77YZ3678wUOk8+SxAdJdPa6YI/qaF4hH1O4r6LaW6uu4p+2dN3nJvDt27ZYurccsqFlkZc1FVAyAOJgy8wgaNrYrEHN2mmrxu2qvZh0ZTuNQei+XII9GBqwcSNfKiIfiLezC8lD8U1ekNPFrBGyPcKZQN5R0kLhS4w4Q2ozEEK5hdu8BHz0MTfxlcyeOmvtl0nu9Pdv9PEuTSxTi2owDrXYm+xUFNhc6FK40k=
